# Generated by Django 4.0.6 on 2022-07-16 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnitImport',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0fb837be-bafb-469f-b060-348476263960'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], default='OFFER', max_length=10)),
                ('parentId', models.UUIDField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitStatisticUnit',
            fields=[
                ('statid', models.UUIDField(default=uuid.UUID('fe92253a-018a-41c4-8933-c714584f0cdd'), editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('590afacc-f430-4924-b0ab-34eed011ee7c'), editable=False)),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], default='OFFER', max_length=10)),
                ('date', models.DateTimeField()),
                ('parentId', models.UUIDField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitStatisticResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('86eeaf03-9ed2-4599-a968-3ac202f2af94'), primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='api.shopunitstatisticunit')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='api.shopunitimport')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ddc78545-0ba7-4ccd-9f86-ef607f173ebd'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], default='OFFER', max_length=10)),
                ('parentId', models.UUIDField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, to='api.shopunit')),
            ],
        ),
    ]
